development:
  facebook:
    app-id: 18
    app-secret: cc
  twitter:
    consumer-key: p9
    consumer-secret: 5L
  vkontakte:
    app-id: 22
    app-secret: fV


test:
  facebook:
    app-id: 18
    app-secret: cc
  twitter:
    consumer-key: p9
    consumer-secret: 5L
  vkontakte:
    app-id: 22
    app-secret: fV

production:
  facebook:
    app-id: secret
    app-secret: secret
  twitter:
    consumer-key: secret
    consumer-secret: secret
  vkontakte:
    app-id: secret
    app-secret: secret
